name: Main

on:
  push:
    branches: [ main ]
  pull_request: { }


jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
      - run: terraform fmt -check

  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
      - run: terraform init -backend=false
      - run: terraform validate

  plan:
    runs-on: ubuntu-latest
    needs: [fmt, validate]
    concurrency: production
    if: success() && github.event_name == 'pull_request'
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_SA_JSON }}
      GITHUB_TOKEN: ${{ secrets.TERRAFORM_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
      - run: terraform init
      - run: terraform plan

  apply:
    runs-on: ubuntu-latest
    needs: [fmt, validate]
    concurrency: production
    if: success() && github.ref_name == github.event.repository.default_branch
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_SA_JSON }}
      GITHUB_TOKEN: ${{ secrets.TERRAFORM_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
      - run: terraform init
      - run: terraform apply -auto-approve
